title: Pirátská strana Praha
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praha.pirati.cz" # the base hostname & protocol for your site

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/
    teams:
    output: true
    permalink: /program/:title/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar:
        - foto
        - people
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar:
         - team-summary
         - teams-toc
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
      #         - garant
         - program

calendar:
fb: https://www.facebook.com/CeskaPiratskaStranaPraha/
tw: piratipraha

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
